plugins {
  alias(libs.plugins.android.application) apply false
  alias(libs.plugins.android.library) apply false
  alias(libs.plugins.kotlin.android) apply false
  alias(libs.plugins.kotlin.compose) apply false
  alias(libs.plugins.vanniktech.maven.publish) apply false
  alias(libs.plugins.paparazzi) apply false
}

allprojects {
  repositories {
    google()
    mavenCentral()
  }
}

tasks.register('clean', Delete) {
  delete rootProject.layout.buildDirectory
}
