buildscript {
  ext.versions = [
    compileSdk: 34,
    kotlin: '1.9.24',
    flexmark: '0.64.0',
    compose: '1.5.14',
    composeUi: '1.2.0',
  ]

  repositories {
    google()
    mavenCentral()
    maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
  }

  dependencies {
    classpath "com.android.tools.build:gradle:8.1.4"
    classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$versions.kotlin"
    classpath "com.vanniktech:gradle-maven-publish-plugin:0.21.0"
    classpath "org.jetbrains.dokka:dokka-gradle-plugin:1.6.10"
    classpath "app.cash.paparazzi:paparazzi-gradle-plugin:1.3.4"
  }
}

allprojects {
  repositories {
    google()
    mavenCentral()
    maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
  }
}

task clean(type: Delete) {
  delete rootProject.buildDir
}
