[versions]
kotlin = "2.3.20"
agp = "8.13.2"  # https://maven.google.com/web/index.html?q=gradle.plugin#com.android.library:com.android.library.gradle.plugin
compileSdk = "36"
androidx-compose-ui = "1.11.0-rc01"   # https://developer.android.com/jetpack/androidx/releases/compose-ui
androidx-compose-ui-material3 = "1.5.0-alpha17"  # https://developer.android.com/jetpack/androidx/releases/compose-material3
androidx-compose-ui-material-icons = "1.7.8"  # https://developer.android.com/jetpack/androidx/releases/compose-material
androidx-activity = "1.13.0"  # https://developer.android.com/jetpack/androidx/releases/activity
androidx-appcompat = "1.7.1"
flexmark = "0.64.8"
extendedspans = "1.4.0"
kotlinx-coroutines = "1.10.2"
kotlinx-treesitter = "0.24.1"   # https://github.com/tree-sitter/kotlin-tree-sitter/releases
junit = "4.13.2"
truth = "1.4.5"
assertk = "0.28.1"
paparazzi = "2.0.0-alpha02" # https://github.com/cashapp/paparazzi/releases
dropshots = "0.6.0" # https://github.com/dropbox/dropshots/releases
androidx-test = "1.7.0" # https://developer.android.com/jetpack/androidx/releases/test
androidx-test-ext-junit = "1.3.0"
mavenPublish = "0.36.0"
composeLintChecks = "1.4.2" # https://github.com/slackhq/compose-lints/releases

[libraries]
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "androidx-compose-ui" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "androidx-compose-ui" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "androidx-compose-ui" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "androidx-compose-ui-material3" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "androidx-compose-ui-material-icons" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
flexmark-java = { module = "com.vladsch.flexmark:flexmark-java", version.ref = "flexmark" }
flexmark-ext-gfm-strikethrough = { module = "com.vladsch.flexmark:flexmark-ext-gfm-strikethrough", version.ref = "flexmark" }
extendedspans = { module = "me.saket.extendedspans:extendedspans", version.ref = "extendedspans" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-treesitter = { module = "io.github.tree-sitter:ktreesitter", version.ref = "kotlinx-treesitter" }
junit = { module = "junit:junit", version.ref = "junit" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
assertk = { module = "com.willowtreeapps.assertk:assertk", version.ref = "assertk" }
composeLintChecks = { module = "com.slack.lint.compose:compose-lint-checks", version.ref = "composeLintChecks" }
dropshots = { module = "com.dropbox.dropshots:dropshots", version.ref = "dropshots" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidx-test" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext-junit" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "androidx-compose-ui" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "androidx-compose-ui" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
vanniktech-maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }
paparazzi = { id = "app.cash.paparazzi", version.ref = "paparazzi" }
dropshots = { id = "com.dropbox.dropshots", version.ref = "dropshots" }
kotlinx-treesitter = { id = "io.github.tree-sitter.ktreesitter-plugin", version.ref = "kotlinx-treesitter" }
