plugins {
  alias(libs.plugins.android.library)
  alias(libs.plugins.kotlin.android)
  alias(libs.plugins.kotlin.compose)
  alias(libs.plugins.vanniktech.maven.publish)
  alias(libs.plugins.paparazzi)
}

android {
  namespace "me.saket.wysiwyg"
  resourcePrefix "wysiwyg_"

  compileSdk libs.versions.compileSdk.get().toInteger()
  defaultConfig.minSdk 23

  buildFeatures {
    compose = true
    buildConfig = true
  }
  kotlinOptions {
    jvmTarget = "17"
  }
  java {
    toolchain.languageVersion.set(JavaLanguageVersion.of(17))
  }
  lint {
    abortOnError true
  }
}

dependencies {
  api libs.flexmark.java
  api libs.flexmark.ext.gfm.strikethrough
  api libs.extendedspans
  api libs.kotlinx.coroutines.core

  implementation libs.androidx.compose.ui
  implementation libs.androidx.compose.foundation

  lintChecks libs.composeLintChecks

  testImplementation libs.junit
  testImplementation libs.truth
  testImplementation libs.assertk
  testImplementation libs.kotlinx.coroutines.test
  testImplementation libs.turbine
}
